const data = {
    users: [
      {
        name: 'JJonhy',
        email: 'admin@usp.com',
        password: '123456',
        isAdmin: true,
      },
      {
        name: 'Dilvan',
        email: 'dilvan@usp.com',
        password: '123456',
        isAdmin: false,
      },
    ],
    products: [
      {
        // _id: 1,
        name: 'DILVAN WATCH',
        slug: 'dilvan-watch',
        category: 'HOMEM',
        fotinha: "images/rel1/1.jpg",
        price: 560.90,
        countInStock: 79,
        brand: 'Dilvan God',
        rating: 4.5,
        numReviews: 965,
        description: 'High Quality',
      },
      {
        // _id: 2,
        name: 'JJONHY WATCH',
        slug: 'jjonhy-watch',
        category: 'HOMEM',
        fotinha: 'images/rel2/1.jpg',
        price: 290.90,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.73,
        numReviews: 8478,
        description: 'High Quality',
      },
      {
        // _id: 3,
        name: 'PETER WATCH',
        slug: 'peter-watch',
        category: 'MULHER',
        fotinha: 'images/rel3/1.jpg',
        price: 25,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'High Quality Product',
      },
      {
        // _id: 4,
        name: 'YARD WATCH',
        slug: 'yard-watch',
        category: 'HOMEM',
        fotinha: 'images/rel4/1.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        // _id: 5,
        name: 'OMINITRIX',
        slug: 'ominitrix-watch',
        category: 'HOMEM',
        fotinha: 'images/rel5/1.jpg',
        price: 485.90,
        countInStock: 566,
        brand: 'Puma',
        rating: 4.35,
        numReviews: 369,
        description: 'high quality product',
      },
      {
        // _id: 6,
        name: 'MONKEY D. LUFFY',
        slug: 'luffy-watch',
        category: 'HOMEM',
        fotinha: 'images/rel6/1.jpg',
        price: 695.90,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 1014,
        description: 'high quality product',
      },
    ],
  };
export default data;
  