const data = {
    users: [
      {
        name: 'JJonhy',
        email: 'admin@usp.com',
        password: '123456',
        isAdmin: true,
      },
      {
        name: 'Dilvan',
        email: 'dilvan@usp.com',
        password: '123456',
        isAdmin: false,
      },
    ],
    products: [
      {
        // _id: 1,
        name: 'DILVAN WATCH',
        slug: 'dilvan-watch',
        category: 'MEN',
        fotinha: "images/rel1/1.jpg",
        price: 560.90,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality',
      },
      {
        // _id: 2,
        name: 'JJONHY WATCH',
        slug: 'jjonhy-watch',
        category: 'MEN',
        fotinha: 'images/rel2/1.jpg',
        price: 250,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality',
      },
      {
        // _id: 3,
        name: 'PETER WATCH',
        slug: 'peter-watch',
        category: 'WOMEN',
        fotinha: 'images/rel3/1.jpg',
        price: 25,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        // _id: 4,
        name: 'YARD WATCH',
        slug: 'yard-watch',
        category: 'MEN',
        fotinha: 'images/rel4/1.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
    ],
  };
export default data;
  