const data = {
    products: [
      {
        name: 'DILVAN WATCH',
        slug: 'dilvan-watch',
        category: 'MEN',
        image: "images/rel1/1.jpg",
        price: 560.90,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality',
      },
      {
        name: 'JJONHY WATCH',
        slug: 'jjonhy-watch',
        category: 'MEN',
        image: 'images/rel2/1.jpg',
        price: 250,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality',
      },
      {
        name: 'PETER WATCH',
        slug: 'peter-watch',
        category: 'WOMEN',
        image: 'images/rel3/1.jpg',
        price: 25,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        name: 'YARD WATCH',
        slug: 'yard-watch',
        category: 'MEN',
        image: 'images/rel4/1.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
    ],
  };
  module.exports = data
  